name: sc-course-2026
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - h5py
  - anndata
  - scanpy
  - matplotlib
  - seaborn
  - xgboost
  - scikit-learn
  - shap
  - pytorch
  - leidenalg
  - python-igraph
  - louvain
  - tqdm
  - pyarrow
  - ipykernel
  - jupyterlab
